name: ROS1 CI/CD Pipeline for Melodic

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-18.04

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up ROS Melodic
    - name: Set up ROS Melodic
      uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: "melodic"

    # Step 3: Cache Dependencies
    - name: Cache rosdep Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.ros/rosdep/cache
        key: ${{ runner.os }}-rosdep-${{ hashFiles('src/**') }}
        restore-keys: ${{ runner.os }}-rosdep-

    # Step 4: Install dependencies using rosdep
    - name: Install Dependencies
      run: |
        sudo apt-get update
        source /opt/ros/melodic/setup.bash
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

    # Step 5: Build the ROS workspace (parallelized)
    - name: Build Workspace
      run: |
        source /opt/ros/melodic/setup.bash
        catkin_make -j$(nproc)

    # Step 6: Run Unit Tests
    - name: Run Tests
      run: |
        source /opt/ros/melodic/setup.bash
        catkin_make run_tests -j$(nproc)
        catkin_test_results

    # Step 7: Static Analysis with cppcheck (optional cache)
    - name: Static Analysis with cppcheck
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --std=c++14 src/
